# Generated by Django 4.2.4 on 2023-11-19 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demoapp', '0002_product_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_comments',
            name='name_cmt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmt_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('liked', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='product_comments',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmt', to='demoapp.post'),
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
