# Generated by Django 4.2.4 on 2023-11-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_alter_product_comments_name_cmt_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
