# Generated by Django 4.2.4 on 2023-11-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_remove_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_comments',
            name='name_cmt',
        ),
        migrations.RemoveField(
            model_name='product_comments',
            name='product_name',
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.DeleteModel(
            name='product_comments',
        ),
    ]
