# Generated by Django 4.2.4 on 2023-11-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_rename_product_name_product_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
